### PR TITLE
Fixed function highlighting

### PR DESCRIPTION
**Pull request by hossenlopp**
- fixed function highlighting from breaking the highlighting for remainder of document
- attempted to add function call highlighting, only works with non double-quoted calls

### CODE REVIEW

**Comment by hossenlopp** [comment]
@cmoesel you interested in this PR? I wanted functions to not break highlighting and for function calls to be highlighted to make measure reviews easier.

**Comment by cmoesel** [comment]
Sure.  I know I wrote this, but it was a really long time ago.  Can you point me to some instructions regarding how I can easily test this code locally before merging it?  I forget how to load local code as an extension -- but I expect you must have just figured it out, so it's probably fresh in your mind?

That said, feel free to just tell me to RTM if I'm being too lazy.

**Comment by hossenlopp** [comment]
You should be able to add my repo as a remote in your existing checked out copy of the package assuming you have it installed.
- `cd ~/.atom/packages/language-cql`
- `git remote add hossenlopp git@github.com:hossenlopp/atom_cql_support.git`
- `git checkout function_highlighting`
- Reload Atom window by hitting Ctrl+Alt+Command+L

**Comment by cmoesel** [comment]
Yeah, I dig it.  Nice work!

**Comment by brynrhodes** [comment]
+1, thank you! I use this all the time, but have never had a chance to update it!

**Comment by cmoesel** [comment]
I just published the updated package to apm, so you should be able to install the update through the Atom settings UI now.

**Comment by brynrhodes** [comment]
Hooray! Looks fantastic!

**Pull request merged**
